# Generated by Django 5.1.1 on 2026-03-30 17:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("date_applied", models.DateField(default=django.utils.timezone.now)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Internship", "Internship"),
                            ("Full Time", "Full Time"),
                            ("Contract", "Contract"),
                            ("Remote", "Remote"),
                            ("Hybrid", "Hybrid"),
                            ("Onsite", "Onsite"),
                        ],
                        default="Full Time",
                        max_length=20,
                    ),
                ),
                (
                    "ctc",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CTC/Stipend (e.g., 12 LPA, 50k/month)",
                        max_length=100,
                    ),
                ),
                ("application_link", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Applied", "Applied"),
                            ("OA", "Online Assessment"),
                            ("Shortlisted", "Shortlisted"),
                            ("Interview", "Interview"),
                            ("HR Round", "HR Round"),
                            ("Rejected", "Rejected"),
                            ("Offer", "Offer"),
                            ("Accepted", "Accepted"),
                        ],
                        default="Applied",
                        max_length=20,
                    ),
                ),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("response_notes", models.TextField(blank=True, default="")),
                (
                    "resume_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g., Resume_V1_AI_ML, Resume_V2_FullStack",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
                "ordering": ["-date_applied"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date_applied"],
                        name="application_user_id_db321b_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="application_user_id_16fc9d_idx"
                    ),
                    models.Index(
                        fields=["follow_up_date"], name="application_follow__e1f345_idx"
                    ),
                ],
            },
        ),
    ]
